### ISSUE TITLE
File is larger than the maximum allowed (64 KB)

### ISSUE THREAD

**Issue by mordrax** [justinmimbs/elm-module-graph#1]
I'm trying to do a comparison of a mid sized project ( 35k loc ) before and after a re-architecture however, the before case generates a 78821 bytes file which does not load but gives the above error.

btw, this project is amazing! We needed something like this to aid in figuring out our architectural issues but had to go with intuition and blogs instead. Didn't realise this existed.

edit:
Running elm-reactor locally, I cannot get either before/after to show the graph, after selecting the module-graph.json file, there is no other response and one message:
![image](https://user-images.githubusercontent.com/4709169/31322105-c4d0fc82-acdc-11e7-8728-80ee4185f6bb.png)

**Comment by justinmimbs** [comment]
Hi Joseph, sorry for the trouble! I increased the max allowed file size (you can pull from master if you're running locally), and I updated the github.io page as well. The 64 KB limit was arbitrary, and enforced in the ports.js file. Let me know if you have any more trouble, and thanks for letting me know how you're using it. Hope it's helpful. :)

**Comment by mordrax** [comment]
@justinmimbs thanks for the fast response! It's loading the file now but hitting a [cyclical issue](https://github.com/justinmimbs/elm-module-graph/issues/3)
