### ISSUE TITLE
cyclical dependency involving third party package

### ISSUE THREAD

**Issue by mordrax** [justinmimbs/elm-module-graph#3]
Our project compiles using elm-make fine, however, elm-module-graph complains there is a cycle:

![image](https://user-images.githubusercontent.com/4709169/31322602-82959152-ace6-11e7-95ea-2c5120b3bee4.png)

This goes on for 3000+ and it all has the FormatNumber module in the middle of it.

edit:
I've tried to replicate it without success by doing:

1. Creating two files with cyclical dependency but not importing them in the elm make.
2. Adding the FormatNumber library to another project and importing it the same way:
```
import FormatNumber
import FormatNumber.Locales exposing (Locale, usLocale)
```

**Comment by justinmimbs** [comment]
My guess is that your project has a module named Helpers? The elm-format-number package contains an unexposed module called Helpers, and my script follows unexposed package modules too. I'll update the script stop including unexposed modules....

**Comment by mordrax** [comment]
That makes alot of sense, let me try renaming it and see if it works, will update this issue.

**Comment by mordrax** [comment]
@justinmimbs Thanks, that was the problem.

And I've just 'discovered' what was causing our dependency issue from looking at the graph. It makes it soooo easy!

**Comment by justinmimbs** [comment]
Right on. :) The script still has the issue of including unexposed package modules in a global namespace, which can cause a conflict when it shouldn't need to (like your Helpers and elm-format-number's internal Helpers). So I'm going to re-open this until I can fix that. Thanks for your reports!
