### ISSUE TITLE
Please add support for Elm 0.19

### ISSUE THREAD

**Issue by sandeep-datta** [justinmimbs/elm-module-graph#6]
See title. Thanks.

**Comment by justinmimbs** [comment]
Hi Sandeep,

Sorry for the delay! I don't have near-term plans to update this to support 0.19, but in the meantime, there exist these tools for analyzing module dependencies of a 0.19 project:

https://discourse.elm-lang.org/t/visualizing-module-dependencies-with-kite/2788
https://github.com/stil4m/elm-analyse

Hope this helps,

Justin
